monitor.alsa.rules = [
  {
    matches = [
      { node.name = "alsa_input.pci-0000_05_00.6.analog-stereo" }
    ]
    actions = {
      update-props = {
        audio.volume = 0.67
        device.default-input-port = "analog-input-headset-mic"
      }
    }
  }
]
